services:
  - type: web
    name: eduplatform-backend
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma db push --accept-data-loss && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: BASE_URL
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PAYSTACK_PLAN_PRO_CODE
        sync: false
      - key: PAYSTACK_PLAN_UNLIMITED_CODE
        sync: false
      - key: PAYSTACK_PLAN_PRO_AMOUNT
        value: "999"
      - key: PAYSTACK_PLAN_UNLIMITED_AMOUNT
        value: "1999"
